gText_WouldYouLikeToRestYourPkmn::
	.string "Hello, and welcome to\n"
	.string "the POKéMON CENTER.\p"
	.string "We roll tired POKéMON back to\n"
	.string "the last known-good state.\p"
	.string "Shall I redeploy your POKéMON?$"

gText_IllTakeYourPkmn::
	.string "Sure, I'll redeploy them.\n"
	.string "Give me a few seconds.$"

gText_RestoredPkmnToFullHealth::
	.string "Thanks for waiting.\p"
	.string "Your POKéMON are back to a\n"
	.string "green, passing build.$"

gText_WeHopeToSeeYouAgain::
	.string "Thanks for shipping with us!$"

gText_WelcomeCutShort::
	.string "Hello, and welcome to\n"
	.string "the POKéMON CENTER.\p"
	.string "We roll tired POKéMON back to\n"
	.string "the last known-good state.\p"
	.string "Would you like to…$"

gText_NoticesGoldCard::
	.string "Th-that card…\n"
	.string "Could it be… The GOLD CARD?!\p"
	.string "Oh, the gold color is brilliant!\n"
	.string "The four stars seem to sparkle!\p"
	.string "I've seen several TRAINERS with\n"
	.string "a SILVER CARD before, but, {PLAYER},\l"
	.string "you're the first TRAINER I've ever\l"
	.string "seen with a GOLD CARD!\p"
	.string "Okay, {PLAYER}, please allow me\n"
	.string "the honor of resting your POKéMON!$"

gText_YouWantTheUsual::
	.string "Good to see you, {PLAYER}!\n"
	.string "The usual redeploy, am I right?$"

gText_IllTakeYourPkmn2::
	.string "Sure, I'll redeploy them.\n"
	.string "Just a few seconds.$"

gText_ThankYouForWaiting::
	.string "Thank you for waiting.$"

gText_WeHopeToSeeYouAgain2::
	.string "Thanks for shipping with us!$"
